### ISSUE TITLE
build broken on Mac OS x

### ISSUE THREAD

**Issue by DannyCork** [Swoffa/SublimeKickAssemblerC64#2]
Hi there,
I'm running 10.12.6 with Sublime Text Build 3126 , Vice 1.3 and JDK 8 update 144

When I press F5 I get the following 

[//------------------------------------------------------
//------------------------------------------------------
//          Kick Assembler v4.13 (GUBB Release)         
//------------------------------------------------------
//------------------------------------------------------
parsing
flex pass 1
flex pass 2
flex pass 3
Output pass

Memory Map
----------
Default-segment:
  $0801-$080c Basic
  $080e-$080d Basic End
  $080e-$086e Main Startup
  $0b00-$0b6a ExamplePart

Writing prg file: /Users/x/Desktop/bin/Startup_Compiled.prg
Writing Vice symbol file: /Users/x/Desktop/bin/Startup.vs
Writing Symbol file: bin/Startup.sym
opening dynamic library libavformat.57.dylib failed! error: dlopen(libavformat.57.dylib, 5): image not found

Exiting...

Unknown option '+confirmexit'.
Error parsing command-line options, bailing out. For help use '-help'
[Finished in 0.8s with exit code 255]
[cmd: ["mkdir -p bin & java cml.kickass.KickAssembler 'Startup.asm' -log 'bin/Startup_BuildLog.txt' -o 'bin/Startup_Compiled.prg' -vicesymbols -showmem -symbolfiledir bin && x64 +confirmexit -moncommands 'bin/Startup.vs' 'bin/Startup_Compiled.prg'"]]
[dir: /Users/x/Desktop]
[path: /usr/bin:/bin:/usr/sbin:/sbin]](url)

**Looks like there are possibly multiple issues:

1. opening dynamic library libavformat.57.dylib failed! error: dlopen(libavformat.57.dylib, 5): image not found

2. Unknown option '+confirmexit'.

Anyone else confirm this ?**

**Comment by naali** [comment]
@DannyCork, I ran into similar problem since it seems that +confirmexit isn't supported in VICE 3.1 for OS X... I made a quick patch, so you might want to try it out: https://github.com/Swoffa/SublimeKickAssemblerC64/pull/3

However it seems that you might still be missing something else, since I'm not seeing that error about missing libavformat -library.

**Comment by Swoffa** [comment]
@DannyCork, sorry to be slow in replying. I will look at the PR from @naali and hopefully merge it soon. With the other error, I think it is related to the Sublime installation, and not to Kick Assembler or the Kick Assembler Sublime package. I saw someone having a similar issue before, and i think some kind of reinstall of Sublime resolved it.

@naali: Thanks!

**Comment by Muttley** [comment]
Looks like the +confirmexit command has been renamed to +confirmonexit in VICE 3.1 (not checked other versions)

**Comment by Swoffa** [comment]
I ended up removing the `confirmexit` argument all together, since it seems to differ in different versions/distributions of Vice. In MacOS SDL version it is `confirmonexit` and on MacOS Cocoa version it is `confirmexit`. It is easy to get rid of the warning by configuring the default setting for Vice.

Available in version 1.1.5, here on GitHub and thru Package Control.

And SORRY again for the mega super ultra delay. Busy busy. Thanks everyone for helping, and thanks @DannyCork and @Muttley for the pull requests.
