### ISSUE TITLE
Execute "bat" file

### ISSUE THREAD

**Issue by BacchusFLT** [Swoffa/SublimeKickAssemblerC64#34]
I still dearly miss the option of a key to execute a batch file. F7 assembles the current file and F5 assembles a project, but my projects are built around a bat (we can call it make.bat) that crunches files, build all files and creates the d64. 

Can I please get F3 to run make.bat ;-)

**Comment by og2t** [comment]
+1 for this feature. Also, please include the full path to the `make.sh` file, i.e. I often put extra scripts in `scripts` folder `./scripts/make.sh`. Thanks! Digger/ESM

**Comment by Swoffa** [comment]
> +1 for this feature. Also, please include the full path to the `make.sh` file, i.e. I often put extra scripts in project's `scripts` folder `./scripts/make.sh`. Thanks! Digger/ESM
Yes, there will be setting, one for path and one for filename, or something like that.

**Comment by BacchusFLT** [comment]
That is exactly what I want! :-)

Pre and post is of course nice, but that is still pre and post for current file. Your F5 is for your building of a full project but my projects aren't based on on an asm file but a bat file...

**Comment by Swoffa** [comment]
Available in version 1.2.5
PR #35

**Comment by Swoffa** [comment]
@BacchusFLT 
The key is `F8`, since `F3` is already in use for _Find next_, hope it is okay.

Also, the following (relevant?) environment variables will be available in the make script:
`kickass_file`, filename of active file when command was triggered
`kickass_file_path`, full path active file when command was triggered
`kickass_prg_file`, full path for suggested prg file name, for active file when command was triggered
`kickass_bin_folder`, path to current output folder (`bin` or specified by setting `kickass_output_path`)

**Comment by BacchusFLT** [comment]
Oh yes ... Looking forward to availability!

**Comment by og2t** [comment]
Nice!

**Comment by BacchusFLT** [comment]
Thanks :-)

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 Skype: BacchusBerg
 Hangout: pontus.bergatrollet@gmail.com
 www.bergatrollet.se


Den tis 30 okt. 2018 kl 06:26 skrev Simon Oskarsson <
notifications@github.com>:

**Comment by BacchusFLT** [comment]
Works - super!

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 Skype: BacchusBerg
 Hangout: pontus.bergatrollet@gmail.com
 www.bergatrollet.se


Den tis 30 okt. 2018 kl 06:26 skrev Simon Oskarsson <
notifications@github.com>:
