### ISSUE TITLE
Keyboard collision

### ISSUE THREAD

**Issue by BacchusFLT** [Swoffa/SublimeKickAssemblerC64#56]
This from user running windows:

The docs says that "CTRL+Shift+P" should compile the current file and "Control+Shift+P" should compile current file. These are the same keyboard command and it can of course only do one of the things, and what it does is the first one. I miss the option of doing the second.

**Comment by Swoffa** [comment]
Thanks @BacchusFLT for bringing this to my attention. I updated the docs/ReadMe.
`Control+B` builds the current file
`Control+Shift+B` builds startup

**Comment by BacchusFLT** [comment]
Control+B brings up a menu - it doesn't build.

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 Skype: BacchusBerg
 Hangout: pontus.bergatrollet@gmail.com
 www.bergatrollet.se


Den ons 3 juni 2020 kl 13:43 skrev Simon Oskarsson <notifications@github.com

**Comment by Swoffa** [comment]
Yes, true. `Control+B` builds with the "default" build option, if no default build option is selected the menu is shown so that one can be selected, `KickAssemblerC64` means build current file. The next time you use `Control+B` the same build option will be invoked immediately.

So, the documentation is not entirely correct. I will check if an exclusive hot key can be assigned, or update the documentation.

**Comment by Swoffa** [comment]
Documentation  updated.
